"""altering user_id as unique in otp model

Revision ID: 03b91e54ae5e
Revises: e78383417de0
Create Date: 2026-06-22 17:12:06.028399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03b91e54ae5e'
down_revision: Union[str, None] = 'e78383417de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('otp_user_id_key', 'otp', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('otp_user_id_key', 'otp', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###